X

diff --git a/bin/day-clone b/bin/day-clone
--- a/bin/day-clone
+++ b/bin/day-clone
@@ -104,10 +104,10 @@ if [ -d "$destination" ]; then
 fi
 
 # Clone the repo
-echo git clone --branch "$git_tag" "$git_repo" "$destination/daylily" 
-git clone --branch "$git_tag" "$git_repo" "$destination/daylily" || { echo "Git clone failed"; exit 1; }
+echo git clone --branch "$git_tag" "$git_repo" "$destination/daylily-omics-analysis" 
+git clone --branch "$git_tag" "$git_repo" "$destination/daylily-omics-analysis" || { echo "Git clone failed"; exit 1; }
 
-cd "$destination/daylily"
+cd "$destination/daylily-omics-analysis"
 
 cat <<EOF
 
@@ -122,5 +122,5 @@ EOF
 
 echo ""
 echo "TO MOVE TO YOUR NEW ANALYSIS DIRECTORY, run:"
-echo "    cd $clone_root/$user_name/$destination/daylily"
+echo "    cd $clone_root/$user_name/$destination/daylily-omics-analysis"
 echo ""
